server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            admin-key: ${KAKAO_ADMIN_KEY}
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3307/shimpyoso # 아직 안 넣음
    username: ${DB_USERNAME} # 아직 안 넣음
    password: ${DB_PASSWORD} # 아직 안 넣음

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      maxFileSize: 5120MB # ?? 5GB
      maxRequestSize: 5120MB # ?? 5GB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          connectiontimeout: 1000 #1초
          starttls:
            enable: true
  data:
    redis:
      host: ${REDIS_ADDRESS}
      port: ${REDIS_PORT}
jwt:
  secretKey: ${JWT_SECRET}
  secretKeyRT: ${JWT_SECRET_RT}
  expirationRT: 7200000 # 2 hours in milliseconds
  expirationALRT: 2592000000 # 30 days in milliseconds
  expiration: 600000  # 10 min in milliseconds

springdoc:
  swagger-ui:
    path: /api