server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3307/shimpyoso
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      maxFileSize: 5120MB # ?? 5GB
      maxRequestSize: 5120MB # ?? 5GB

  mail:
    host: smtp.gmail.com
    port: 587
    username: anflwkd@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          connectiontimeout: 1000 #1초
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379


jwt:
  secretKey: very-strong-access-secret-key-very-strong-access-secret-key-very-strong-access-secret-key
  secretKeyRT: refresh-token-secret-key
  expirationRT: 86400000
  expiration: 86400000  # 1 day in milliseconds