version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      # 컨테이너가 시작될 때 지정된 데이터베이스가 자동으로 생성. 이미 있을 때는 아무것도 하지 않는다.
      MYSQL_DATABASE: shimpyoso
     #      MYSQL_USER: root
     #      MYSQL_PASSWORD: 1234
    ports:
      - 3307:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4 # 버전 고정 추천
    container_name: elasticsearch
    environment:
      - discovery.type=single-node # 단일 노드 실행
      - xpack.security.enabled=false # 보안(인증) 끔 (개발용)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # JVM 힙 메모리 제한
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data
volumes:
  mariadb_data:
  redis_data:
